#!/usr/bin/env python3
"""
Build base-pair-level segdup density for the 80%-cumulative-length hotspot
subset, as a rolling-window track for track 1 of `11_circos_segdup_hotspot.ipynb`.

The hotspots are the merged segdup intervals that make up the top 80% of total
segdup length (the "80% rule" subset, generated by
`05_cumulative_feature_overlap.ipynb` -> `segdup_hotspots_80percLength.tsv`).
Density is computed over those hotspot intervals only (not the full segdup).

For every chromosome-scale contig, slide a window of `WINDOW_SIZE` bp in steps
of `STEP` bp and compute, per window:
  - total_segdup_intervals : number of hotspot intervals overlapping the window
  - segdup_bp              : total bp of hotspot overlap within the window
  - percent_segdup         : segdup_bp / window_length * 100

Output (written to the current directory):
    segdup_density_rolling_<WINDOW_SIZE>_<STEP>_bpLevel_hotspot80perc.tsv
    columns: Chromosome, Start, End, total_segdup_intervals, segdup_bp,
             percent_segdup

Run with the `genome-assembly` conda environment:

    conda activate genome-assembly
    python build_segdup_density.py
"""

import numpy as np
import pandas as pd
from intervaltree import IntervalTree

# ---------------------------------------------------------------------------
# RUN PARAMETERS
# ---------------------------------------------------------------------------
WINDOW_SIZE = 5_000_000   # rolling window size (bp)
STEP = 100_000            # step between consecutive windows (bp)

# ---------------------------------------------------------------------------
# INPUT PATHS
# ---------------------------------------------------------------------------
# 80%-length segdup hotspots (merged, non-overlapping; from step 5).
HOTSPOTS_TSV = "segdup_hotspots_80percLength.tsv"
# Chromosome lengths (.fai) for the final assembly.
FAI = (
    "/tscc/projects/ps-renlab2/jhc103/degu-genome-assembly-proj/"
    "data/denovo_OctDegus_genome/041425-assembly/"
    "hifiasm-041425-assembly-mitoFiltered-scaffolded-curated-masked-chrNameAssigned/"
    "assembly_final.sorted.headerRenamed.chrAssigned.mito.fasta.fai"
)

OUT_TSV = f"segdup_density_rolling_{WINDOW_SIZE}_{STEP}_bpLevel_hotspot80perc.tsv"


def main():
    # 1. Load 80%-length hotspots (already merged / non-overlapping).
    hotspots = pd.read_csv(HOTSPOTS_TSV, sep="\t")
    hotspots = hotspots[hotspots["Chromosome"].str.startswith("chr")]
    intervals = hotspots[["Chromosome", "Start", "End"]].astype(
        {"Start": int, "End": int}
    )
    print(f"loaded {len(intervals):,} hotspot intervals")

    # 2. Chromosome lengths (chromosome-scale contigs only).
    fai = pd.read_csv(
        FAI, sep="\t", header=None, usecols=[0, 1],
        names=["Chromosome", "Length"],
    )
    fai = fai[fai["Chromosome"].str.startswith("chr")]

    # 3. Generate sliding windows.
    windows = []
    for chrom, length in zip(fai["Chromosome"], fai["Length"]):
        for start in range(0, length, STEP):
            end = min(start + WINDOW_SIZE, length)
            windows.append((chrom, start, end))
    windows_df = pd.DataFrame(windows, columns=["Chromosome", "Start", "End"])
    print(f"generated {len(windows_df):,} windows "
          f"({WINDOW_SIZE:,} bp / {STEP:,} bp step)")

    # 4. Density per window (over hotspot intervals).
    trees = {
        chrom: IntervalTree.from_tuples(zip(g["Start"], g["End"]))
        for chrom, g in intervals.groupby("Chromosome")
    }
    total_bp = np.zeros(len(windows_df), dtype=np.int64)
    total_intervals = np.zeros(len(windows_df), dtype=int)
    for i, row in windows_df.iterrows():
        tree = trees.get(row["Chromosome"])
        if tree:
            overlaps = tree[row["Start"]:row["End"]]
            total_intervals[i] = len(overlaps)
            total_bp[i] = sum(
                min(row["End"], iv.end) - max(row["Start"], iv.begin)
                for iv in overlaps
            )

    window_lengths = (windows_df["End"] - windows_df["Start"]).to_numpy()
    percent = np.divide(
        total_bp, window_lengths,
        where=window_lengths > 0,
        out=np.zeros_like(total_bp, dtype=float),
    ) * 100

    final = windows_df.assign(
        total_segdup_intervals=total_intervals,
        segdup_bp=total_bp,
        percent_segdup=percent,
    )

    final.to_csv(OUT_TSV, sep="\t", index=False)
    print(f"saved {OUT_TSV} ({len(final):,} rows)")
    print(f"percent_segdup: max={final['percent_segdup'].max():.2f} "
          f"mean={final['percent_segdup'].mean():.3f} "
          f">0={100 * (final['percent_segdup'] > 0).mean():.1f}%")


if __name__ == "__main__":
    main()
